<?php

/**
 * This is the model base class for the table "authassignment".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Authassignment".
 *
 * Columns in table "authassignment" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $itemname
 * @property integer $userid
 * @property string $bizrule
 * @property string $data
 *
 */
abstract class BaseAuthassignment extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'authassignment';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Authassignment|Authassignments', $n);
	}

	public static function representingColumn() {
		return array(
			'itemname',
			'userid',
		);
	}

	public function rules() {
		return array(
			array('itemname, userid', 'required'),
			array('userid', 'numerical', 'integerOnly'=>true),
			array('itemname', 'length', 'max'=>64),
			array('bizrule, data', 'safe'),
			array('bizrule, data', 'default', 'setOnEmpty' => true, 'value' => null),
			array('itemname, userid, bizrule, data', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'itemname' => null,
			'userid' => null,
			'bizrule' => Yii::t('app', 'Bizrule'),
			'data' => Yii::t('app', 'Data'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('itemname', $this->itemname);
		$criteria->compare('userid', $this->userid);
		$criteria->compare('bizrule', $this->bizrule, true);
		$criteria->compare('data', $this->data, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}