<?php

/**
 * This is the model base class for the table "authitemchild".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Authitemchild".
 *
 * Columns in table "authitemchild" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $parent
 * @property string $child
 *
 */
abstract class BaseAuthitemchild extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'authitemchild';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Authitemchild|Authitemchildren', $n);
	}

	public static function representingColumn() {
		return 'parent';
	}

	public function rules() {
		return array(
			array('parent, child', 'required'),
			array('parent, child', 'length', 'max'=>64),
			array('parent, child', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'parent' => null,
			'child' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('parent', $this->parent);
		$criteria->compare('child', $this->child);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}